import Head from 'next/head';
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react';
import styles from '@/styles/Home.module.css';
import { LinearProgress } from '@mui/material';
import dynamic from 'next/dynamic';
import axios from 'axios';
import { useSnackbar } from 'notistack';
import DynamicComponentLoader from '@/components/common/loader/dynemicComploader';

const Navbar = dynamic(() => import('../../components/navbar'), {
  ssr: false,
  loading: () => (
    <div
      style={{
        width: '100%',
      }}
    >
      <LinearProgress />
    </div>)
});

const ProjectDetailsWrapper = dynamic(() => import('../../components/modules/projectDetails'), {
  ssr: false,
  loading: () => (
    <div
      style={{
        width: '100%',
      }}
    >
      <LinearProgress />
    </div>)
});

const ProjectDetails = () => {
    const router=useRouter();
    const id=router.query.projectId;
    const [projectDetailsData,setProjectDetailsData]=useState(null);
    // console.log('test id',id)
  const { enqueueSnackbar } = useSnackbar();
    useEffect(()=>{
      if(id){
        axios.get(`http://localhost:5000/get-property/${id}`)
          .then(res => setProjectDetailsData(res.data))
           .catch((error:any) => enqueueSnackbar((error.message), { variant: 'error' }))
      }
    },[id])
  return (
    <>
      <Head>
        <title>AIP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Navbar />
        {projectDetailsData ? < ProjectDetailsWrapper data={projectDetailsData[0]} />:<DynamicComponentLoader/ >}
      </div>
    </>
  )
}

export default ProjectDetails