import Head from 'next/head';
import { useRouter } from 'next/router'
import React from 'react';
import styles from '@/styles/Home.module.css';
import { LinearProgress } from '@mui/material';
import dynamic from 'next/dynamic';

const Navbar = dynamic(() => import('../../components/navbar'), {
  ssr: false,
  loading: () => (
    <div
      style={{
        width: '100%',
      }}
    >
      <LinearProgress />
    </div>)
});

const ProjectDetailsWrapper = dynamic(() => import('../../components/modules/projectDetails'), {
  ssr: false,
  loading: () => (
    <div
      style={{
        width: '100%',
      }}
    >
      <LinearProgress />
    </div>)
});

const ProjectDetails = () => {
    const router=useRouter();
    const id=router.query.projectId;
    console.log('test id',id)
  return (
    <>
      <Head>
        <title>AIP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Navbar />
        < ProjectDetailsWrapper />
      </div>
    </>
  )
}

export default ProjectDetails