import Head from 'next/head'
import React, { useEffect, useMemo, useState } from 'react';
import styles from '@/styles/Home.module.css';
import dynamic from 'next/dynamic';
import { LinearProgress } from '@mui/material';
import { useRouter } from 'next/router';
import { useSnackbar } from 'notistack';
import axios from 'axios';

const Navbar = dynamic(() => import('../../components/navbar'), {
    ssr: false,
    loading: () => (
        <div
            style={{
                width: '100%',
            }}
        >
            <LinearProgress />
        </div>)
});

const EditProperty = dynamic(() => import('../../components/modules/editproperty'), {
    ssr: false,
    loading: () => (
        <div
            style={{
                width: '100%',
            }}
        >
            <LinearProgress />
        </div>)
});

const AboutUs = () => {
    const router = useRouter();
    const id = useMemo(()=>router.query.editproperty,[router]);
    const [projectDetailsData, setProjectDetailsData] = useState(null);
    // console.log('test id',id)
    const { enqueueSnackbar } = useSnackbar();
    useEffect(() => {
        if (id) {
            console.log('test id',id)
            axios.get(`http://localhost:5000/get-property/${id}`)
                .then(res => setProjectDetailsData(res.data))
                .catch((error: any) => enqueueSnackbar((error.message), { variant: 'error' }))
        }
    }, [id])
    return (
        <>
            <Head>
                <title>AIP</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <Navbar />
                < EditProperty data={projectDetailsData} />
                {/* <HomePage /> */}
                {/* <Footer /> */}
            </div>
        </>
    )
}

export default AboutUs